food=input("Name a food > ")
plant=input("Name a type of plant > ")
method=input("Name a method of cooking > ")
burned=input("What word describes burned food? > ")
DIY=input("Name a DIY item > ")
print("\n")
m=input(" ")
print(method ,food ,"with ",burned ,plant ,"on a bed of ",DIY)